name: fcn_torch
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - torchvision=
  - torchaudio=
  - click=8.1.7
  - hydra-core=1.3.2
  - seaborn=0.13.2
  - pandas=2.2.1
  - numpy=1.26.4
  - scikit-learn=1.4
  - tqdm=4.66.2
