defaults:
  - _self_
  - model: resnet50_pretrained_fcn32s

name: train_fcn_seg

train_dataloader:
  batch_size: 20
  num_workers: 4
  shuffle: True

val_dataloader:
  batch_size: 1
  num_workers: 4
  shuffle: False

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  num_epochs: 31
  # training loop control
  # in epochs
  checkpoint_every: 1
  val_every: 1
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0

optimizer:
  _target_: torch.optim.SGD
  lr: 1.0e-2
  momentum: 0.9
  weight_decay: 0.0001

checkpoint:
  topk:
    monitor_key: acc
    mode: max
    k: 5
    format_str: epoch={epoch:04d}-acc={acc:.4f}.ckpt
  save_last_ckpt: true

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${model.name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${model.name}
    subdir: ${hydra.job.num}